name: plugin zip

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: wooms-extra
      - run: cd wooms-extra && ls -la
      - name: action-zip
        uses: montudor/action-zip@v0.1.0
        with:
          args: zip -qq -r wooms-extra.zip wooms-extra
      - run: ls -la
      - run: cd wooms-extra & ls -la
      - name: upload-artifact
        uses: actions/upload-artifact@v2
        with:
          name: wooms-extra
          path: wooms-extra-${{ env.VERSION }}.zip
      - name: Upload to release 
        uses: JasonEtco/upload-to-release@master
        with:
          args: wooms-extra-${{ env.VERSION }}.zip application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
